ARG GRAFANA_VERSION=""

FROM grafana/grafana:${GRAFANA_VERSION}

USER root

COPY ./img/*   /usr/share/grafana/public/img/

ENV GF_PATHS_PLUGINS="/var/lib/grafana-plugins"

RUN mkdir -p "$GF_PATHS_PLUGINS"
RUN chown -R grafana:grafana "$GF_PATHS_PLUGINS"

USER grafana

RUN grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install bessler-pictureit-panel
